/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TodayRouteImport } from "./routes/today"
import { Route as SearchRouteImport } from "./routes/search"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TasksIndexRouteImport } from "./routes/tasks/index"
import { Route as StatsIndexRouteImport } from "./routes/stats/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as ServersIndexRouteImport } from "./routes/servers/index"
import { Route as ProjectsIndexRouteImport } from "./routes/projects/index"
import { Route as PlanningIndexRouteImport } from "./routes/planning/index"
import { Route as DatabaseIndexRouteImport } from "./routes/database/index"
import { Route as CredentialsIndexRouteImport } from "./routes/credentials/index"
import { Route as ApiIndexRouteImport } from "./routes/api/index"
import { Route as AboutIndexRouteImport } from "./routes/about/index"
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects/$projectId"
import { Route as ProjectsProjectIdIndexRouteImport } from "./routes/projects/$projectId/index"
import { Route as ProjectsProjectIdPagesPageIdRouteImport } from "./routes/projects/$projectId/pages/$pageId"

const TodayRoute = TodayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: "/stats/",
  path: "/stats/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: "/servers/",
  path: "/servers/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: "/planning/",
  path: "/planning/",
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseIndexRoute = DatabaseIndexRouteImport.update({
  id: "/database/",
  path: "/database/",
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsIndexRoute = CredentialsIndexRouteImport.update({
  id: "/credentials/",
  path: "/credentials/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: "/api/",
  path: "/api/",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/about/",
  path: "/about/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPagesPageIdRoute =
  ProjectsProjectIdPagesPageIdRouteImport.update({
    id: "/pages/$pageId",
    path: "/pages/$pageId",
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/search": typeof SearchRoute
  "/today": typeof TodayRoute
  "/projects/$projectId": typeof ProjectsProjectIdRouteWithChildren
  "/about/": typeof AboutIndexRoute
  "/api/": typeof ApiIndexRoute
  "/credentials/": typeof CredentialsIndexRoute
  "/database/": typeof DatabaseIndexRoute
  "/planning/": typeof PlanningIndexRoute
  "/projects/": typeof ProjectsIndexRoute
  "/servers/": typeof ServersIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/stats/": typeof StatsIndexRoute
  "/tasks/": typeof TasksIndexRoute
  "/projects/$projectId/": typeof ProjectsProjectIdIndexRoute
  "/projects/$projectId/pages/$pageId": typeof ProjectsProjectIdPagesPageIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/search": typeof SearchRoute
  "/today": typeof TodayRoute
  "/about": typeof AboutIndexRoute
  "/api": typeof ApiIndexRoute
  "/credentials": typeof CredentialsIndexRoute
  "/database": typeof DatabaseIndexRoute
  "/planning": typeof PlanningIndexRoute
  "/projects": typeof ProjectsIndexRoute
  "/servers": typeof ServersIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/stats": typeof StatsIndexRoute
  "/tasks": typeof TasksIndexRoute
  "/projects/$projectId": typeof ProjectsProjectIdIndexRoute
  "/projects/$projectId/pages/$pageId": typeof ProjectsProjectIdPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/search": typeof SearchRoute
  "/today": typeof TodayRoute
  "/projects/$projectId": typeof ProjectsProjectIdRouteWithChildren
  "/about/": typeof AboutIndexRoute
  "/api/": typeof ApiIndexRoute
  "/credentials/": typeof CredentialsIndexRoute
  "/database/": typeof DatabaseIndexRoute
  "/planning/": typeof PlanningIndexRoute
  "/projects/": typeof ProjectsIndexRoute
  "/servers/": typeof ServersIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/stats/": typeof StatsIndexRoute
  "/tasks/": typeof TasksIndexRoute
  "/projects/$projectId/": typeof ProjectsProjectIdIndexRoute
  "/projects/$projectId/pages/$pageId": typeof ProjectsProjectIdPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/search"
    | "/today"
    | "/projects/$projectId"
    | "/about/"
    | "/api/"
    | "/credentials/"
    | "/database/"
    | "/planning/"
    | "/projects/"
    | "/servers/"
    | "/settings/"
    | "/stats/"
    | "/tasks/"
    | "/projects/$projectId/"
    | "/projects/$projectId/pages/$pageId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/search"
    | "/today"
    | "/about"
    | "/api"
    | "/credentials"
    | "/database"
    | "/planning"
    | "/projects"
    | "/servers"
    | "/settings"
    | "/stats"
    | "/tasks"
    | "/projects/$projectId"
    | "/projects/$projectId/pages/$pageId"
  id:
    | "__root__"
    | "/"
    | "/search"
    | "/today"
    | "/projects/$projectId"
    | "/about/"
    | "/api/"
    | "/credentials/"
    | "/database/"
    | "/planning/"
    | "/projects/"
    | "/servers/"
    | "/settings/"
    | "/stats/"
    | "/tasks/"
    | "/projects/$projectId/"
    | "/projects/$projectId/pages/$pageId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  TodayRoute: typeof TodayRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  ApiIndexRoute: typeof ApiIndexRoute
  CredentialsIndexRoute: typeof CredentialsIndexRoute
  DatabaseIndexRoute: typeof DatabaseIndexRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/today": {
      id: "/today"
      path: "/today"
      fullPath: "/today"
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search": {
      id: "/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/": {
      id: "/tasks/"
      path: "/tasks"
      fullPath: "/tasks/"
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/stats/": {
      id: "/stats/"
      path: "/stats"
      fullPath: "/stats/"
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/servers/": {
      id: "/servers/"
      path: "/servers"
      fullPath: "/servers/"
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/": {
      id: "/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/planning/": {
      id: "/planning/"
      path: "/planning"
      fullPath: "/planning/"
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/database/": {
      id: "/database/"
      path: "/database"
      fullPath: "/database/"
      preLoaderRoute: typeof DatabaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/credentials/": {
      id: "/credentials/"
      path: "/credentials"
      fullPath: "/credentials/"
      preLoaderRoute: typeof CredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/": {
      id: "/api/"
      path: "/api"
      fullPath: "/api/"
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about/": {
      id: "/about/"
      path: "/about"
      fullPath: "/about/"
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/$projectId": {
      id: "/projects/$projectId"
      path: "/projects/$projectId"
      fullPath: "/projects/$projectId"
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/$projectId/": {
      id: "/projects/$projectId/"
      path: "/"
      fullPath: "/projects/$projectId/"
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    "/projects/$projectId/pages/$pageId": {
      id: "/projects/$projectId/pages/$pageId"
      path: "/pages/$pageId"
      fullPath: "/projects/$projectId/pages/$pageId"
      preLoaderRoute: typeof ProjectsProjectIdPagesPageIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdPagesPageIdRoute: typeof ProjectsProjectIdPagesPageIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdPagesPageIdRoute: ProjectsProjectIdPagesPageIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  TodayRoute: TodayRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  ApiIndexRoute: ApiIndexRoute,
  CredentialsIndexRoute: CredentialsIndexRoute,
  DatabaseIndexRoute: DatabaseIndexRoute,
  PlanningIndexRoute: PlanningIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
